{
 "title": "MinIO",
 "description": "MinIO Grafana Dashboard",
 "tags": [
  "minio",
  "prometheus",
  "storage"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Online/Offline Drives",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_drive_online_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "online"
    },
    {
     "expr": "max(minio_cluster_drive_offline_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "minio_node_go_routine_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_total_bytes{job=~\"$scrape_jobs\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_objects_size_distribution{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_status{job=~\"$scrape_jobs\"}",
     "legendFormat": "Pool: {{pool}} Set: {{set}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_total_bytes{job=~\"$scrape_jobs\"}) by (instance)) - topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (instance))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(minio_cluster_capacity_usable_free_bytes{job=~\"$scrape_jobs\"}) by (instance)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_nodes_online_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Open FDs ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Time Since Last Scan",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_usage_last_activity_nano_seconds{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_process_resident_memory_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Total S3 Ingress",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_received_bytes{job=~\"$scrape_jobs\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_file_descriptor_open_total{job=~\"$scrape_jobs\"}",
     "legendFormat": "Open FDs [{{server}}]"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_bucket_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total S3 Egress",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minio_s3_traffic_sent_bytes{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Scanned Versions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_versions_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_objects_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Finished",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_bucket_scans_finished{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  },
  {
   "title": "Scanned Directories",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(minio_node_scanner_directories_scanned{job=~\"$scrape_jobs\"}[$__rate_interval])",
     "legendFormat": "[{{server}}]"
    }
   ]
  }
 ]
}