ingress:
  enabled: false

adminPassword: "password"

serviceDns:
  loadBalancerIP: 192.168.0.25
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
  type: LoadBalancer

persistentVolumeClaim:
  enabled: true
  storageClass: "longhorn"
