{
 "title": "Node dashboard",
 "tags": [
  "linux",
  "node"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"node-exporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\", mode!=\"idle\"}[6h])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\"}[6h])))) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"$node\",job=\"node-exporter\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"$node\",job=\"node-exporter\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{instance=\"$node\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{instance=\"$node\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together (15 min average)",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_load15{instance=\"$node\",job=\"node-exporter\"}[15m]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\"}[15m]))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\", mode=\"system\"}[24h])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\"}[24h])))",
     "legendFormat": "System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\", mode=\"user\"}[24h])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\"}[24h])))",
     "legendFormat": "User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\", mode=\"nice\"}[24h])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\"}[24h])))",
     "legendFormat": "Nice"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\", mode=\"iowait\"}[24h])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\"}[24h])))",
     "legendFormat": "Iowait"
    }
   ]
  },
  {
   "title": "CPU Frequency Scaling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "CPU {{ cpu }}"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_max_hertz{instance=\"$node\",job=\"node-exporter\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "avg(node_cpu_scaling_frequency_min_hertz{instance=\"$node\",job=\"node-exporter\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"node-exporter\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"node-exporter\"} - (node_memory_Cached_bytes{instance=\"$node\",job=\"node-exporter\"} + node_memory_Buffers_bytes{instance=\"$node\",job=\"node-exporter\"} + node_memory_SReclaimable_bytes{instance=\"$node\",job=\"node-exporter\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_SReclaimable_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Reclaimable"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Stack",
   "type": "timeseries",
   "description": "Apps - Memory used by user-space applications;\n\nPageTables - Memory used to map between virtual and physical memory addresses;\n\nSlab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc);\n\nCache - Parked file data (file content) cache;\n\nBuffers - Block device (e.g. harddisk) cache;\n\nUnused - Free memory unassigned;",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"node-exporter\"} - node_memory_MemFree_bytes{instance=\"$node\",job=\"node-exporter\"} - node_memory_Buffers_bytes{instance=\"$node\",job=\"node-exporter\"} - node_memory_Cached_bytes{instance=\"$node\",job=\"node-exporter\"} - node_memory_Slab_bytes{instance=\"$node\",job=\"node-exporter\"} - node_memory_PageTables_bytes{instance=\"$node\",job=\"node-exporter\"} - node_memory_SwapCached_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "Unused"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\", job=\"node-exporter\", chip=\"platform_coretemp_0\", sensor!=\"temp1\"}",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "RAM temperature",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\", job=\"node-exporter\", chip=\"thermal_thermal_zone0\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\", job=\"node-exporter\", chip=\"platform_coretemp_0\", sensor!=\"temp1\"}*0.95",
     "legendFormat": "{{ sensor }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",job=\"node-exporter\",device=\"eth0\"}[2m])*8",
     "legendFormat": "Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",job=\"node-exporter\",device=\"eth0\"}[$__rate_interval])*8",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$node\",job=\"node-exporter\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$node\",job=\"node-exporter\",mountpoint=\"/\",fstype!=\"rootfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_network_transmit_bytes_total{instance=\"$node\",job=\"node-exporter\",device=\"eth0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\",job=\"node-exporter\"} - node_boot_time_seconds{instance=\"$node\",job=\"node-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}