---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pihole-vault-service-account
  namespace: pihole
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: pihole
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: pihole-vault-role
    serviceAccount: pihole-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pihole-password
  namespace: pihole
  labels:
    app: pihole
    chart: pihole-2.26.1
    release: pihole
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: pihole/password
  refreshAfter: 1h
  destination:
    name: pihole-password
    create: true
