
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-custom-dnsmasq
  namespace: pihole
  labels:
    app: pihole
    chart: pihole-2.26.1
    release: pihole
data:
  02-custom.conf: |
    addn-hosts=/etc/addn-hosts
    dhcp-option=6,192.168.0.25
  addn-hosts: |
  05-pihole-custom-cname.conf: |
