---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: penpot-vault-service-account
  namespace: penpot
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: penpot
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: penpot-vault-role
    serviceAccount: penpot-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: penpot-secret
  namespace: penpot
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: penpot/secret
  refreshAfter: 1h
  destination:
    name: penpot-secret
    create: true

---
apiVersion: v1
kind: Secret
metadata:
  name: penpot-common-secrets
  namespace: penpot
type: Opaque
stringData:
  PENPOT_FLAGS: "disable-registration disable-login-with-password enable-login-with-oidc disable-email-verification enable-smtp enable-prepl-server disable-secure-session-cookies"
  PENPOT_PUBLIC_URI: "https://penpot.keindev.ru"
  PENPOT_BACKEND_URI: "https://penpot.keindev.ru"
  PENPOT_EXPORTER_URI: "https://penpot.keindev.ru/api/export"
  PENPOT_DATABASE_URI: "postgresql://postgres.postgres.svc.cluster.local/penpot"
  PENPOT_REDIS_URI: "redis://redis.redis.svc.cluster.local/0"
  PENPOT_TELEMETRY_ENABLED: "false"
  PENPOT_SMTP_HOST: "http://penpot-mailcatch.penpot.svc.cluster.local"
  PENPOT_SMTP_PORT: 1025
  PENPOT_SMTP_USERNAME: ""
  PENPOT_SMTP_PASSWORD: ""
  PENPOT_SMTP_TLS: "false"
  PENPOT_SMTP_SSL: "false"
  PENPOT_PREPL_HOST: "0.0.0.0"
  PENPOT_ASSETS_STORAGE_BACKEND: "assets-s3"
  PENPOT_STORAGE_ASSETS_S3_ENDPOINT: "http://minio.minio.svc.cluster.local"
  PENPOT_STORAGE_ASSETS_S3_REGION: "homelab"
  PENPOT_STORAGE_ASSETS_S3_BUCKET: "penpot"
  PENPOT_OIDC_BASE_URI: "https://authentik.keindev.ru/application/o/penpot/"
  PENPOT_OIDC_ROLES: ""
  PENPOT_OIDC_ROLES_ATTR: ""
  PENPOT_OIDC_SCOPES: "openid email profile"
  PENPOT_OIDC_NAME_ATTR: "preferred_username"
  PENPOT_OIDC_EMAIL_ATTR: "email"


