---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: penpot-pvc
  namespace: penpot
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
