---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  source:
    path: k8s/kube-prometheus-stack
    repoURL: https://github.com/keindev/homelab.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      selfHeal: true

