---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    path: k8s/traefik
    repoURL: https://github.com/keindev/homelab.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      selfHeal: true

