---
apiVersion: v1
kind: Service
metadata:
  name: mailcatch
  namespace: mailcatch
spec:
  selector:
    app: mailcatch
  ports:
    - name: web
      protocol: TCP
      port: 1080
      targetPort: 1080
    - name: smtp
      protocol: TCP
      port: 1025
      targetPort: 1025
  type: ClusterIP
