---
apiVersion: v1
kind: Service
metadata:
  name: mailcatch
  namespace: mailcatch
spec:
  selector:
    app: mailcatch
  ports:
    - protocol: TCP
      port: 1080
      targetPort: 1080
  type: ClusterIP
