---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-vault-service-account
  namespace: minio
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: minio
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: minio-vault-role
    serviceAccount: minio-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: minio-auth-secret
  namespace: minio
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: minio/auth
  refreshAfter: 1h
  destination:
    name: minio-auth-secret
    create: true


