---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio
  namespace: minio
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`minio.keindev.ru`)
      priority: 10
      services:
        - name: minio
          namespace: minio
          port: 9001
  tls:
    secretName: local-keindev-ru-tls

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-buckets-security
  namespace: minio
spec:
  headers:
    frameDeny: true
    sslRedirect: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000

---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: minio-buckets-transport
  namespace: minio
spec:
  serverName: minio
  insecureSkipVerify: true

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-buckets
  namespace: minio
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`buckets.keindev.ru`)
      services:
        - name: minio
          port: 433
          serversTransport: minio-buckets-transport
      middlewares:
        - name: minio-buckets-security
  tls:
    secretName: local-keindev-ru-tls
