---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: minio
    release: prometheus
    name: minio
  name: minio
  namespace: minio
spec:
  endpoints:
  - port: "9000"
    path: /minio/v2/metrics/cluster
  namespaceSelector:
    matchNames:
    - minio
  selector:
    matchLabels:
      app: minio
