---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pgadmin-vault-service-account
  namespace: pgadmin
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: pgadmin
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: pgadmin-vault-role
    serviceAccount: pgadmin-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: pgadmin/credentials
  refreshAfter: 1h
  destination:
    name: pgadmin-secret
    create: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: pgadmin-config
  namespace: pgadmin
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: pgadmin/config
  refreshAfter: 1h
  destination:
    name: pgadmin-config
    create: true

