---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-vault-service-account
  namespace: longhorn-system
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: longhorn-system
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: longhorn-vault-role
    serviceAccount: longhorn-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cifs-secret
  namespace: longhorn-system
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: longhorn/backup
  refreshAfter: 10s
  destination:
    name: cifs-secret
    create: true


