---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-vault-service-account
  namespace: cert-manager
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: cert-manager
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: cert-manager-vault-role
    serviceAccount: cert-manager-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: cert-manager/token
  refreshAfter: 1h
  destination:
    name: cloudflare-token-secret
    create: true


