---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-exporter-vault-service-account
  namespace: postgres-exporter
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: postgres-exporter
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: postgres-exporter-vault-role
    serviceAccount: postgres-exporter-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-exporter-secret
  namespace: postgres-exporter
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: postgres-exporter/secret
  refreshAfter: 1h
  destination:
    name: postgres-exporter-secret
    create: true


