apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter
  namespace: postgres-exporter
spec:
  selector:
    app: postgres-exporter
  type: ClusterIP
  ports:
    - name: metrics
      protocol: TCP
      port: 9187
      targetPort: 9187

