---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-vault-service-account
  namespace: postgres
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: postgres
spec:
  method: kubernetes
  mount: kubernetes
  namespace: postgres
  kubernetes:
    role: postgres-vault-role
    serviceAccount: postgres-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: postgres-secret
  namespace: postgres
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: postgres/database
  refreshAfter: 1h
  destination:
    name: postgres-secret
    create: true


