---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-vault-service-account
  namespace: grafana
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: grafana
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: grafana-vault-role
    serviceAccount: grafana-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-secret
  namespace: grafana
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: grafana/secret
  refreshAfter: 1h
  destination:
    name: grafana-secret
    create: true

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-common-secret
  namespace: grafana
type: Opaque
stringData:
  GF_SERVER_ROOT_URL: "https://grafana.keindev.ru"
  GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
  GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
  GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authentik.keindev.ru/application/o/authorize/"
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authentik.keindev.ru/application/o/token/"
  GF_AUTH_GENERIC_OAUTH_API_URL: "https://authentik.keindev.ru/application/o/userinfo/"
  GF_AUTH_SIGNOUT_REDIRECT_URL: "https://authentik.keindev.ru/application/o/grafana/end-session/"
  GF_AUTH_OAUTH_AUTO_LOGIN: "true"
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'"



