---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
spec:
  destination:
    namespace: node-exporter
    server: https://kubernetes.default.svc
  source:
    path: k8s/node-exporter
    repoURL: https://github.com/keindev/homelab.git
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true
