---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: authentik-vault-service-account
  namespace: authentik
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: authentik
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: authentik-vault-role
    serviceAccount: authentik-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authentik
  namespace: authentik
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: authentik/environment
  refreshAfter: 1h
  destination:
    name: authentik
    create: true
