auth:
  existingSecret: "minio-auth-secret"

disableWebUI: false

ingress:
  enabled: false

persistence:
  enabled: true
  storageClass: "longhorn"

serviceAccount:
  create: false
  name: "minio-vault-service-account"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/minio/v2/metrics/cluster"
  prometheus.io/port: "9000"

#extraEnvVars:
#  - name: MINIO_BROWSER_REDIRECT_URL
#    value: minio.keindev.ru

hostAliases:
  - ip: "192.168.8.33"
    hostnames:
      - "authentik.keindev.ru"

metrics:
  enabled: false
