---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: affine-vault-service-account
  namespace: affine
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: affine
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: affine-vault-role
    serviceAccount: affine-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: affine-secret
  namespace: affine
  labels:
    created-by: vault-secrets-operator
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: affine/secret
  refreshAfter: 1h
  destination:
    name: affine-secret
    create: true

---
apiVersion: v1
kind: Secret
metadata:
  name: affine-common-secret
  namespace: penpot
type: Opaque
stringData:
  NODE_OPTIONS: "--import=./scripts/register.js"
  AFFINE_CONFIG_PATH: "/root/.affine/config"
  REDIS_SERVER_HOST: "redis.redis.svc.cluster.local"
  NODE_ENV: "production"
  TELEMETRY_ENABLE: "false"
