---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-config-pvc
  namespace: affine
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-storage-pvc
  namespace: affine
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
