---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: plane-vault-service-account
  namespace: plane
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: static-auth
  namespace: plane
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: plane-vault-role
    serviceAccount: plane-vault-service-account
    audiences:
      - vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: plane-secret
  namespace: plane
spec:
  vaultAuthRef: static-auth
  mount: kv-v2
  type: kv-v2
  path: plane/secret
  refreshAfter: 1h
  destination:
    name: plane-secret
    create: true




